#!/usr/bin/env python3
"""Generate docs/INDEX.md from the YAML-like frontmatter of docs/**/*.md.

Frontmatter format (kept deliberately simple, no PyYAML needed):
  ---
  id: ADR-0001
  title: Some title
  type: adr            # adr | pitch | spec | initiative | guide | eval
  status: accepted
  date: 2026-10-01
  modules: [NumioCore, cli]   # inline lists only
  tags: [layout, release]
  owner: name
  supersedes: ADR-0000
  ---
  TL;DR: one line summary.

Usage:
  python3 scripts/build-index.py           # write docs/INDEX.md
  python3 scripts/build-index.py --check   # validate metadata and fail if INDEX.md is stale (CI)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "INDEX.md"
REQUIRED = ["id", "title", "type", "status", "date"]
TYPE_ORDER = ["pitch", "adr", "spec", "initiative", "eval", "guide"]
SKIP_DIRS = {"briefs"}          # working files, not indexed
SKIP_FILES = {"INDEX.md", "README.md"}


def parse(text):
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return None, text
    meta = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, val = line.split(":", 1)
        val = val.split(" #")[0].strip()
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip() for v in val[1:-1].split(",") if v.strip()]
        meta[key.strip()] = val
    return meta, m.group(2)


def tldr(body):
    for line in body.splitlines():
        if line.strip().startswith("TL;DR:"):
            return line.strip()[len("TL;DR:"):].strip()
        if line.strip():
            # TL;DR must be the first non-empty line after the frontmatter
            break
    return ""


def collect():
    docs, problems = [], []
    for path in sorted(DOCS.rglob("*.md")):
        rel = path.relative_to(ROOT)
        if path.name in SKIP_FILES or SKIP_DIRS & set(path.relative_to(DOCS).parts[:-1]):
            continue
        meta, body = parse(path.read_text(encoding="utf-8"))
        if meta is None:
            problems.append(f"{rel}: missing frontmatter")
            continue
        missing = [k for k in REQUIRED if not meta.get(k)]
        if missing:
            problems.append(f"{rel}: missing keys {missing}")
            continue
        t = tldr(body)
        if not t:
            problems.append(f"{rel}: missing 'TL;DR:' as first line after frontmatter")
        meta["_path"] = str(rel)
        meta["_tldr"] = t
        docs.append(meta)
    ids = {}
    for d in docs:
        if d["id"] in ids:
            problems.append(f"duplicate id {d['id']}: {ids[d['id']]} and {d['_path']}")
        ids[d["id"]] = d["_path"]
    return docs, problems


def render(docs):
    def lst(v):
        return ", ".join(v) if isinstance(v, list) else (v or "")

    out = [
        "<!-- GENERATED by scripts/build-index.py. Do not edit by hand. -->",
        "# Docs Index",
        "",
        "Agents: grep this file by module/tag/status, then open only matching docs (TL;DR first).",
        "",
    ]
    by_type = {}
    for d in docs:
        by_type.setdefault(d["type"], []).append(d)
    for t in TYPE_ORDER + sorted(set(by_type) - set(TYPE_ORDER)):
        items = by_type.get(t)
        if not items:
            continue
        out += [f"## {t}", "", "| id | title | status | modules | tags | path | TL;DR |", "|---|---|---|---|---|---|---|"]
        for d in sorted(items, key=lambda x: x["id"]):
            cells = [d["id"], d["title"], d["status"], lst(d.get("modules")), lst(d.get("tags")),
                     f"`{d['_path']}`", d["_tldr"].replace("|", "/")]
            out.append("| " + " | ".join(cells) + " |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    docs, problems = collect()
    content = render(docs)
    if check:
        if problems:
            print("\n".join(problems))
        stale = not INDEX.exists() or INDEX.read_text(encoding="utf-8") != content
        if stale:
            print("docs/INDEX.md is stale: run python3 scripts/build-index.py")
        sys.exit(1 if problems or stale else 0)
    INDEX.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX.relative_to(ROOT)} ({len(docs)} docs)")
    if problems:
        print("Warnings:\n" + "\n".join("  " + p for p in problems))


if __name__ == "__main__":
    main()