name: Build and Release macOS CLI

on:
  push:
    tags:
      - 'v*'  # Це запускає workflow, коли пушиться тег, що починається з "v" (наприклад, v1.0.0)

jobs:
  build:
    runs-on: macos-latest  # Виконання на найновішій версії macOS

    steps:
      # Крок 1: Checkout репозиторію
      - name: Checkout repository
        uses: actions/checkout@v2

      # Крок 2: Налаштування Swift (macOS runner вже має Swift)
      - name: Set up Swift
        run: |
          swift --version  # Перевірка версії Swift

      # Крок 3: Побудова проекту для macOS у конфігурації Release
      - name: Build the project for macOS
        run: |
          swift build -c release

      # Крок 4: Створення ZIP архіву для macOS
      - name: Create ZIP archive for macOS
        run: |
          VERSION=$(git describe --tags --abbrev=0)  # Отримуємо останній тег для версії
          mkdir -p output  # Створюємо директорію для архіву
          cp .build/release/numio output/  # Копіюємо збудований файл
          zip -r "numio-cli-${VERSION}-macOS.zip" output/numio  # Архівуємо файл
          mv "numio-cli-${VERSION}-macOS.zip" output/  # Переміщаємо ZIP до папки output

      # Крок 5: Завантаження архіву на GitHub Releases
      - name: Upload release asset to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: output/numio-cli-*.zip  # Завантажуємо всі файли ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для авторизації
